Integrate Zuul CI/CD
opentelekomcloud/docker-machine-opentelekomcloud pull request #54
Opened 2021-02-24 11:53 UTC by lego963

Replace Travis CI/CD with Zuul CI/CD pipeline

2021-02-24 11:57 UTC, anton-sidelnikov submitted a review, later dismissed

2021-02-24 12:00 UTC, outcatcher requested changes

2021-02-24 12:00 UTC, outcatcher commented on README.md
> +[![Zuul Gate](https://zuul.eco.tsi-dev.otc-service.com/api/tenant/eco/badge?project=opentelekomcloud/docker-machine-opentelekomcloud&pipeline=check&branch=master)](https://zuul.eco.tsi-dev.otc-servic
The branch should be `devel`

2021-02-24 12:13 UTC, lego963 commented
recheck

2021-02-24 12:50 UTC, lego963 commented
recheck

2021-02-24 12:54 UTC, lego963 commented
recheck

2021-02-24 13:09 UTC, anton-sidelnikov submitted a review, later dismissed

2021-02-24 13:22 UTC, outcatcher commented on .goreleaser.yml
> +  - format: zip
Please make sure `zip` works with Rancher

2021-02-25 08:02 UTC, lego963 commented
recheck

2021-02-25 08:28 UTC, anton-sidelnikov approved these changes, later dismissed

2021-02-25 08:30 UTC, outcatcher approved these changes, later dismissed

2021-02-25 08:37 UTC, lego963 commented
recheck

2021-02-25 08:52 UTC, anton-sidelnikov approved these changes

2021-02-25 08:55 UTC, outcatcher approved these changes

2021-02-25 08:56 UTC, merged